[app]
secretKey = "ASDFASDFASDF" # hashStatecode
rootURL = "http://localhost:9001"
baseURL = "/login/"
[auth]
# Login cookie name
loginCookieName = "juno_session"
# The lifetime (days) an authenticated user can be inactive before being required to login at next visit. Default is 7 days.
# 接口授权用户
loginMaximumInactiveLifetimeDays = 7
# The maximum lifetime (days) an authenticated user can be logged in since login time before being required to login. Default is 30 days.
# 页面登录用户
loginMaximumLifetimeDays = 30
# How often should auth tokens be rotated for authenticated users when being active. The default is each 10 minutes.
# 刷新时间
tokenRotationIntervalMinutes = 10
# Set to true to disable (hide) the login form, useful if you use OAuth
disableLoginForm = false
# Set to true to disable the signout link in the side menu. useful if you use auth.proxy
disableSignoutMenu = false
# URL to redirect the user to after sign out
signoutRedirectUrl = ""
# Set to true to attempt login with OAuth automatically, skipping the login screen.
# This setting is ignored if multiple OAuth providers are configured.
oauthAutoLogin = false
# OAuth state max age cookie duration. Defaults to 60 seconds.
oauthStateCookieMaxAge = 60
# limit of api_key seconds to live before expiration
apiKeyMaxSecondsToLive = -1

[[auth.tps]]
typ = "github"
enable = true
allowSignUp = true
clientId = "xxx"
clientSecret = "xxx"
scopes = ["user:email", "read:org"]
authUrl = "https://github.com/login/oauth/authorize"
tokenUrl = "https://github.com/login/oauth/access_token"
apiUrl = "https://api.github.com/user"
allowedDomains = []
teamIds = []
allowedOrganizations = []


[server.http]
port = 9001
