// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package nws

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson390c608bDecodeGithubComKl7snToolkitNws(in *jlexer.Lexer, out *CompatMsgDataItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "type":
			out.Type = string(in.String())
		case "data":
			if m, ok := out.Data.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Data.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Data = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson390c608bEncodeGithubComKl7snToolkitNws(out *jwriter.Writer, in CompatMsgDataItem) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Type != "" {
		const prefix string = ",\"type\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	if in.Data != nil {
		const prefix string = ",\"data\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if m, ok := in.Data.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Data.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Data))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CompatMsgDataItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson390c608bEncodeGithubComKl7snToolkitNws(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CompatMsgDataItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson390c608bEncodeGithubComKl7snToolkitNws(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CompatMsgDataItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson390c608bDecodeGithubComKl7snToolkitNws(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CompatMsgDataItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson390c608bDecodeGithubComKl7snToolkitNws(l, v)
}
func easyjson390c608bDecodeGithubComKl7snToolkitNws1(in *jlexer.Lexer, out *CompatMsg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "event":
			out.Event = string(in.String())
		case "data":
			if m, ok := out.Data.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Data.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Data = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson390c608bEncodeGithubComKl7snToolkitNws1(out *jwriter.Writer, in CompatMsg) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Event != "" {
		const prefix string = ",\"event\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Event))
	}
	if in.Data != nil {
		const prefix string = ",\"data\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if m, ok := in.Data.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Data.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Data))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CompatMsg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson390c608bEncodeGithubComKl7snToolkitNws1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CompatMsg) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson390c608bEncodeGithubComKl7snToolkitNws1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CompatMsg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson390c608bDecodeGithubComKl7snToolkitNws1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CompatMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson390c608bDecodeGithubComKl7snToolkitNws1(l, v)
}
